[package]
name = "marble"
version = "0.1.0"
authors = ["Tyler Neely <t@jujit.su>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
bincode = "1.3.3"
crc32fast = "1.2.1"
lazy_static = "1.4.0"
zipf = "7.0.0"
backtrace = "0.3.63"
