[package]
name = "marble"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
panic = "abort"

[dev-dependencies]
env_logger = "0.9.0"
serde = { version = "1.0", features = ["derive"] }

[dependencies]
crc32fast = "1.3.2"
log = "0.4.16"
zstd = "0.11.1"
fs2 = "0.4.3"
pagetable = "0.2.5"
