[package]
name = "marble"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
crc32fast = "1.3.2"
log = "0.4.16"
zstd = "0.11.1+zstd.1.5.2"
fuzzcheck = { version = "0.11.0", optional = true }
fs2 = "0.4.3"
pagetable = "0.2.4"
