[package]
name = "marble"
version = "0.1.0"
authors = ["Tyler Neely <t@jujit.su>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.5.3"
fst = "0.4.4"
memmap = "0.7.0"
