[package]
name = "marble"
authors = ["Tyler Neely <t@jujit.su>"]
version = "7.7.7"
edition = "2021"
description = "garbage-collecting on-disk object store"
license = "GPL-3.0"
repository = "https://github.com/komora-io/marble"
documentation = "https://docs.rs/marble/"

[profile.release]
debug = true
panic = "abort"

[dev-dependencies]
env_logger = "0.9.0"

[dependencies]
crc32fast = "1.3.2"
log = "0.4.16"
zstd = "0.11.1"
fs2 = "0.4.3"
pagetable = "0.2.5"
serde = { version = "1.0", features = ["derive"], optional = true }
bincode = { version = "1.3.3", optional = true }
